apiVersion: apps/v1
kind: Deployment
metadata:
  name: omri-flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omri-flask-app
  template:
    metadata:
      labels:
        app: omri-flask-app
    spec:
      containers:
        - name: omri-flask-app
          image: omriyan01/flask-app:latest
          ports:
            - containerPort: 5455  #
