apiVersion: v1
kind: Service
metadata:
  name: omri-flask-app-service
spec:
  selector:
      app: flask-app
  type: LoadBalancer
  ports:
    - name: omri-flask-app
      port: 5441 # Port exposed by your Flask application
      targetPort: 5455 # Port your Flask application is listening on

